services:
  nginx:
    container_name: flowcheck-nginx
    image: nginx:1.27-alpine
    restart: on-failure:3
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./certbot-data/conf:/etc/letsencrypt
      - ./certbot-data/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - flowcheck-network

  frontend:
    container_name: flowcheck-frontend
    image: ${DOCKER_USERNAME}/${FRONTEND_IMAGE:-flowcheck-frontend}:latest
    restart: on-failure:3
    networks:
      - flowcheck-network

  backend:
    container_name: flowcheck-backend
    image: ${DOCKER_USERNAME}/${BACKEND_IMAGE:-flowcheck-backend}:latest
    restart: on-failure:3
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - flowcheck-network

networks:
  flowcheck-network:
    driver: bridge