-- 커뮤니티 게시글 좋아요
create table if not exists public.community_post_likes (
    id bigint generated by default as identity primary key,
    post_id bigint not null references public.community_posts(post_id) on delete cascade,
    user_id uuid not null references public.users(user_id) on delete cascade,
    created_at timestamptz not null default now(),
    constraint uk_community_post_likes_post_user unique (post_id, user_id)
);

create index if not exists idx_community_post_likes_post_id
    on public.community_post_likes(post_id);

-- 커뮤니티 게시글 댓글·답글
create table if not exists public.community_post_comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null references public.community_posts(post_id) on delete cascade,
    user_id uuid not null references public.users(user_id) on delete cascade,
    parent_id bigint references public.community_post_comments(id) on delete cascade,
    content varchar(500) not null,
    created_at timestamptz not null default now(),
    constraint ck_community_post_comments_content
        check (char_length(btrim(content)) between 1 and 500)
);

create index if not exists idx_community_post_comments_post_parent_created
    on public.community_post_comments(post_id, parent_id, created_at);

create index if not exists idx_community_post_comments_user_created
    on public.community_post_comments(user_id, created_at desc);

-- 브라우저 직접 접근은 막고 백엔드 API를 통해서만 처리합니다.
alter table public.community_post_likes enable row level security;
alter table public.community_post_comments enable row level security;
