import React from 'react';
import { TrendingUp, RefreshCw } from 'lucide-react';
import { ResponsiveContainer, LineChart, Line, CartesianGrid, XAxis, YAxis, Tooltip, Legend } from 'recharts';

interface Domain {
  id: number;
  domainUrl: string;
  verified: boolean;
}

interface LoadChartDataPoint {
  time: string;
  users: number;
  tps: number;
  avg_response: number;
}

interface LoadMetrics {
  maxTps: number;
  avgResponse: number;
  errorRate: number;
  bottleneckDiagnosis: string;
}

interface LoadPageProps {
  domains: Domain[];
  selectedLoadDomain: number;
  setSelectedLoadDomain: (id: number) => void;
  vusers: number;
  setVusers: (v: number) => void;
  duration: number;
  setDuration: (d: number) => void;
  loadPrompt: String;
  setLoadPrompt: (p: string) => void;
  loadStatus: string;
  loadMetrics: LoadMetrics | null;
  loadChartData: LoadChartDataPoint[];
  handleRunLoadTest: () => void;
}

export default function LoadPage({
  domains,
  selectedLoadDomain,
  setSelectedLoadDomain,
  vusers,
  setVusers,
  duration,
  setDuration,
  loadPrompt,
  setLoadPrompt,
  loadStatus,
  loadMetrics,
  loadChartData,
  handleRunLoadTest
}: LoadPageProps) {
  return (
    <div style={{ textAlign: 'left' }}>
      <h2 style={{ fontSize: '1.75rem', marginBottom: '1.5rem' }}>Locust Intelligent Load Testing Engine</h2>
      
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 2.5fr', gap: '2rem' }}>
        <div>
          <div className="card">
            <h3 style={{ marginBottom: '1.25rem' }}>Configure Load Test</h3>

            <div className="form-group">
              <label className="form-label">Target Website</label>
              <select 
                className="form-input" 
                value={selectedLoadDomain} 
                onChange={(e) => setSelectedLoadDomain(parseInt(e.target.value))}
              >
                {domains.filter(d => d.verified).map(d => (
                  <option key={d.id} value={d.id}>{d.domainUrl}</option>
                ))}
              </select>
            </div>

            <div className="form-group">
              <label className="form-label">Virtual Users (VUsers): {vusers}</label>
              <input 
                type="range" 
                min="10" 
                max="500" 
                step="10"
                value={vusers} 
                onChange={(e) => setVusers(parseInt(e.target.value))}
                style={{ accentColor: 'var(--accent)' }}
              />
            </div>

            <div className="form-group">
              <label className="form-label">Test Duration: {duration} seconds</label>
              <input 
                type="range" 
                min="10" 
                max="120" 
                step="10"
                value={duration} 
                onChange={(e) => setDuration(parseInt(e.target.value))}
                style={{ accentColor: 'var(--accent)' }}
              />
            </div>

            <div className="form-group">
              <label className="form-label">Scenario Prompt Requirements</label>
              <textarea 
                className="form-input" 
                rows={3} 
                value={loadPrompt.toString()}
                onChange={(e) => setLoadPrompt(e.target.value)}
              ></textarea>
            </div>

            <button 
              className="btn btn-primary" 
              style={{ width: '100%', marginTop: '1rem' }}
              onClick={handleRunLoadTest}
              disabled={loadStatus === 'running'}
            >
              {loadStatus === 'running' ? 'Running Load Test...' : 'Generate & Run Test'}
            </button>
          </div>
        </div>

        <div>
          <div className="card" style={{ minHeight: '400px' }}>
            <h3 style={{ marginBottom: '1.25rem' }}>Telemetry Metrics & Charts</h3>

            {loadStatus === 'idle' && (
              <div style={{ color: 'var(--text-muted)', textAlign: 'center', paddingTop: '6rem' }}>
                <TrendingUp size={48} style={{ margin: '0 auto 1rem', opacity: 0.3 }} />
                <p>Locust script will be dynamically generated by Gemini and executed headlessly.</p>
              </div>
            )}

            {loadStatus === 'running' && (
              <div style={{ textAlign: 'center', paddingTop: '5rem' }}>
                <RefreshCw className="animate-spin" size={40} style={{ margin: '0 auto 1.5rem', color: 'var(--accent)' }} />
                <p>Gemini generating `locustfile.py` and running traffic simulation...</p>
              </div>
            )}

            {loadStatus === 'success' && loadMetrics && (
              <div>
                <div className="dashboard-grid" style={{ gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem', marginBottom: '1.5rem' }}>
                  <div className="card" style={{ padding: '1rem', textAlign: 'center' }}>
                    <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Max TPS</div>
                    <div style={{ fontSize: '1.5rem', fontWeight: 700, color: 'var(--success)' }}>{loadMetrics.maxTps.toFixed(1)} req/s</div>
                  </div>
                  <div className="card" style={{ padding: '1rem', textAlign: 'center' }}>
                    <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Avg Response Time</div>
                    <div style={{ fontSize: '1.5rem', fontWeight: 700 }}>{loadMetrics.avgResponse.toFixed(0)} ms</div>
                  </div>
                  <div className="card" style={{ padding: '1rem', textAlign: 'center' }}>
                    <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Error Rate</div>
                    <div style={{ fontSize: '1.5rem', fontWeight: 700, color: loadMetrics.errorRate > 0 ? 'var(--error)' : 'var(--success)' }}>
                      {loadMetrics.errorRate.toFixed(1)}%
                    </div>
                  </div>
                </div>

                {/* Line Chart */}
                <div style={{ height: '300px', width: '100%', marginBottom: '2rem' }}>
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={loadChartData}>
                      <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                      <XAxis dataKey="time" stroke="var(--text-muted)" />
                      <YAxis yAxisId="left" stroke="var(--accent)" />
                      <YAxis yAxisId="right" orientation="right" stroke="var(--success)" />
                      <Tooltip contentStyle={{ backgroundColor: 'var(--bg-secondary)', borderColor: 'var(--border)' }} />
                      <Legend />
                      <Line yAxisId="left" type="monotone" dataKey="avg_response" name="Response Time (ms)" stroke="var(--accent)" activeDot={{ r: 8 }} />
                      <Line yAxisId="right" type="monotone" dataKey="tps" name="TPS (req/s)" stroke="var(--success)" />
                    </LineChart>
                  </ResponsiveContainer>
                </div>

                <div className="markdown-body" style={{ background: 'var(--bg-tertiary)', padding: '1.5rem', borderRadius: '0.5rem', border: '1px solid var(--border)' }}>
                  <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit' }}>{loadMetrics.bottleneckDiagnosis}</pre>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
